# Generated by Django 2.1.2 on 2018-10-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('user_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user_screenname', models.CharField(blank=True, max_length=200, null=True)),
                ('user_location', models.CharField(blank=True, max_length=500, null=True)),
                ('user_followers', models.IntegerField(default=0)),
                ('user_friends', models.IntegerField(default=0)),
                ('t_id', models.IntegerField(default=0)),
                ('t_rtcount', models.IntegerField(default=0)),
                ('t_favcount', models.IntegerField(default=0)),
                ('t_create', models.DateTimeField(blank=True, null=True)),
                ('t_text', models.TextField(blank=True)),
                ('lang', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
